name: Feature Request
description: Suggest an idea for this project
title: '[Feature]: '
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Before submitting, please search [existing issues](https://github.com/Zephyruso/zashboard/issues) to see if your idea has already been proposed.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Please provide a clear and concise description of the feature you'd like to request
      placeholder: 'Please describe the feature you want in detail'
    validations:
      required: true

  - type: textarea
    id: why-needed
    attributes:
      label: Why is this feature needed?
      description: Explain why this feature is important and how it will improve the project or user experience
      placeholder: 'Explain the importance and value of this feature'
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: List the scenarios or use cases where this feature will be applied
      placeholder: |
        Use case 1:
        Use case 2:
        Use case 3:
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, examples, or references that would help understand the feature request
      placeholder: 'Other relevant information, examples, or references'
    validations:
      required: false
